%module "math"
%include ../Angle.i
%include ../GaussMarkovProcess.i
%include ../Rand.i
%include ../RollingMean.i
%include ../Vector2.i
%include ../Vector3.i
%include ../Vector4.i
%include ../Color.i
%include ../Spline.i
